CREATE TABLE USUARIOS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tipo_conta VARCHAR(255) NOT NULL,
    login VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL
);

CREATE TABLE conta_bancaria (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    agencia INT NOT NULL DEFAULT 1,
    conta VARCHAR(255) NOT NULL,
    saldo DOUBLE NOT NULL DEFAULT 0,
    usuario_id BIGINT,
    FOREIGN KEY (usuario_id) REFERENCES USUARIOS(id)
);